/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Identity */
        get: operations["current_identity_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_content_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/topics/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Topic */
        post: operations["discover_topic_api_v1_content_topics_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/packages/{content_package_id}/{content_version}/lessons/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_api_v1_content_packages__content_package_id___content_version__lessons__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Submission */
        post: operations["accept_submission_api_v1_sessions__session_id__submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_v1_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Next Step */
        get: operations["get_next_step_api_v1_submissions__submission_id__next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_operations_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptPurpose
         * @enum {string}
         */
        AttemptPurpose: "assessment" | "practice" | "transfer";
        /**
         * DiagnosticStatus
         * @enum {string}
         */
        DiagnosticStatus: "supported" | "uncertain";
        /** EvaluationView */
        EvaluationView: {
            outcome_verdict: components["schemas"]["OutcomeVerdict"];
            reasoning_verdict: components["schemas"]["ReasoningVerdict"];
            /** @default supported */
            diagnostic_status: components["schemas"]["DiagnosticStatus"];
            /** Evidence References */
            evidence_references?: string[];
            /** Misconception Id */
            misconception_id?: string | null;
        };
        /** EvidenceSource */
        EvidenceSource: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Title */
            source_title: string;
            /** Source Url */
            source_url: string;
            explanation: components["schemas"]["LocalizedText"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobView */
        JobView: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
        };
        /** LessonDetail */
        LessonDetail: {
            /** Item Id */
            item_id: string;
            title: components["schemas"]["LocalizedText"];
            prompt: components["schemas"]["LocalizedText"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSource"][];
            /** Rubric */
            rubric: components["schemas"]["RubricCriterion"][];
        };
        /** LessonSummary */
        LessonSummary: {
            /** Item Id */
            item_id: string;
            title: components["schemas"]["LocalizedText"];
            prompt: components["schemas"]["LocalizedText"];
        };
        /** LocalizedText */
        LocalizedText: {
            /** En */
            en: string;
            /** Ar */
            ar: string;
        };
        /** NextItemView */
        NextItemView: {
            /** Item Id */
            item_id: string;
            purpose: components["schemas"]["AttemptPurpose"];
            prompt: components["schemas"]["LocalizedText"];
        };
        /** NextStepView */
        NextStepView: {
            /**
             * Action
             * @enum {string}
             */
            action: "pending" | "retry" | "remediation" | "transfer" | "complete" | "failed";
            message: components["schemas"]["LocalizedText"];
            remediation?: components["schemas"]["LocalizedText"] | null;
            next_item?: components["schemas"]["NextItemView"] | null;
        };
        /**
         * OutcomeVerdict
         * @enum {string}
         */
        OutcomeVerdict: "correct" | "incorrect" | "unverified";
        /** PackageSummary */
        PackageSummary: {
            /** Content Package Id */
            content_package_id: string;
            /** Content Version */
            content_version: string;
            /** Topic */
            topic: string;
            /** Lessons */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /** Principal */
        Principal: {
            /** Issuer */
            issuer: string;
            /** Subject */
            subject: string;
        };
        /**
         * ReasoningVerdict
         * @enum {string}
         */
        ReasoningVerdict: "sound" | "partial" | "incorrect" | "insufficient";
        /** RubricCriterion */
        RubricCriterion: {
            /** Criterion Id */
            criterion_id: string;
            description: components["schemas"]["LocalizedText"];
        };
        /** SessionCreate */
        SessionCreate: {
            /** Content Package Id */
            content_package_id: string;
            /** Content Version */
            content_version: string;
            /**
             * Ui Locale
             * @enum {string}
             */
            ui_locale: "ar" | "en";
            /**
             * Instructional Language
             * @enum {string}
             */
            instructional_language: "ar" | "en";
        };
        /** SessionView */
        SessionView: {
            /** Content Package Id */
            content_package_id: string;
            /** Content Version */
            content_version: string;
            /**
             * Ui Locale
             * @enum {string}
             */
            ui_locale: "ar" | "en";
            /**
             * Instructional Language
             * @enum {string}
             */
            instructional_language: "ar" | "en";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubmissionCreate */
        SubmissionCreate: {
            /** Item Id */
            item_id: string;
            /** Answer */
            answer: string;
            /** Reasoning */
            reasoning?: string | null;
            /** @default assessment */
            purpose: components["schemas"]["AttemptPurpose"];
            /** Parent Submission Id */
            parent_submission_id?: string | null;
        };
        /** SubmissionView */
        SubmissionView: {
            /** Item Id */
            item_id: string;
            /** Answer */
            answer: string;
            /** Reasoning */
            reasoning?: string | null;
            /** @default assessment */
            purpose: components["schemas"]["AttemptPurpose"];
            /** Parent Submission Id */
            parent_submission_id?: string | null;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Content Package Id */
            content_package_id: string;
            /** Content Version */
            content_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job: components["schemas"]["JobView"];
            evaluation?: components["schemas"]["EvaluationView"] | null;
        };
        /** TopicDiscoveryRequest */
        TopicDiscoveryRequest: {
            /** Query */
            query: string;
        };
        /** TopicDiscoveryResponse */
        TopicDiscoveryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "unsupported";
            /** Options */
            options: components["schemas"]["LessonSummary"][];
            /** Content Package Id */
            content_package_id?: string | null;
            /** Content Version */
            content_version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_identity_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
        };
    };
    list_packages_api_v1_content_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageSummary"][];
                };
            };
        };
    };
    discover_topic_api_v1_content_topics_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_v1_content_packages__content_package_id___content_version__lessons__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_package_id: string;
                content_version: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_submission_api_v1_sessions__session_id__submissions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_v1_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_step_api_v1_submissions__submission_id__next_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextStepView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_operations_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
